channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - snakemake
  - fastqc
  - samtools=1.4
  - bcftools
  - trimmomatic
  - bwa
  - picard
  - varscan
  - qualimap
  - sra-tools
    #- gatk=3
    #- vardict-java
    #- bowtie2
    #- yara
    #- snpeff
    #- snpsift
    #- freebayes
    #- somatic-sniper
    #- pindel
    #- bioconductor-deepsnv
    #- vardict-java
    #- vardict
